### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by C00reNUT** [provos/parallax-maker#1]
Hello,

thank you for making this open and public!- it's a neat idea using the inpainting from the recent models combined with better depth estimation models, I can imagine that especially inpainting will be much more precise than the 3D video techniques published in the recent years...

I wanted to ask you two things:

1. I there some command line interface pipeline one could use? I didn't go through the code yet, I just read the readme, so sorry if I am asking for something obvious. 
2. How long does it take to render one video, approximately?

Thank you!

**Comment by provos** [comment]
1. There isn't a real CLI. Some of the python files have CLI options but they are not documented and mostly used for just quickly reproducing problems.
2. Assuming you export GLTF to Unreal or Blender and normal options, rendering a 100 frames takes a few minutes.
